# Generated by Django 4.0.4 on 2022-06-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='CourseTeachers',
            new_name='CoursesTeachers',
        ),
    ]
